version: '3'
services:
  jenkins_devops:
    container_name: jenkins
    build: jenkins
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - $PWD/mvn-repo:/root/.m2/repository
    networks:
      - net
networks:
  net:
